config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about", as: "about"

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end

  get '/search', to: 'searchs#search'

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @groups = Group.all
  end

  def show
    @user = User.find(current_user.id)
    @book = Book.new
    @group = Group.find(params[:id])
end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to groups_path
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    GroupMailer.send_mail(@mail_title, @mail_content, group_users).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model:group, local:true do |f| %>

  <% if group.errors.any? %>
    <div id="error_explanation">
      <%= group.errors.count %> error prohibited this obj from being saved:
      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.file_field :image, accept: "image/*", class: "w-100" %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/groups/_list.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
    <tr>
      <td></td>
      <td><%= link_to group.name, group_path(group) %></td>
      <td><%= group.introduction %></td>
      <td><%= group.users.count %></td>
      <td>
        <% if current_user.id == group.owner_id %>
          <%= link_to "Edit", edit_group_path(group), class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class='container px-5 px-sm-0'>
  <div class="row">
    <div class="col-md-8">
      <%= render "form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <div class='row'>
        <%= render 'users/info', user: @user %>

        <div class='col'>
          <% if current_user != @user %>
            <% if (current_user.following? @user) && (@user.following? current_user)  %>
              <%= link_to 'Begin Chat', chat_path(@user.id), class:"btn btn-sm btn-info" %>
            <% end %>
          <% end %>
        </div>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <%= render "groups/list", groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render "form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2><%= @group.name %>メンバーへのメール</h2>
    <%= form_with url: group_send_mail_path(@group),method: :get, local: true do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :mail_title,class:'form-control'%>
        </div>
    <div class="form-group">
        <%=f.label:content %>
        <%= f.text_area :mail_content,class:'form-control' %>
    </div>
    <div>
    <%= f.submit'送信' %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3 class="margin_top text-center">送信が完了しました</h3>
      <div class="main_width">
      <div class="margin_top">内容は以下の通りです。</div>
        <div class="small_margin_top">
          [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
        </div>
        <div>
          [本文]<p class="font-weight-bold"> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <div class='row'>
        <%= render 'users/info', user: @user %>

        <div class='col'>
          <% if current_user != @user %>
            <% if (current_user.following? @user) && (@user.following? current_user)  %>
              <%= link_to 'Begin Chat', chat_path(@user.id), class:"btn btn-sm btn-info" %>
            <% end %>
          <% end %>
        </div>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |member| %>
                <%= member.name %><br>
              <% end %>
            </td>
            <td>
              <% if current_user.id == @group.owner_id %>
                <%= link_to "Notice an Event", group_new_mail_path(@group), class: "btn btn-warning" %>
              <% end %>
            </td>
            <td>
              <% if @group.users.include?(current_user) %>
                <%= link_to "Leave this group", group_path(@group.id), method: :delete, class: "btn btn-danger" %>
              <% else %>
                <%= link_to "Join this group", group_join_path(@group.id), method: :get, class: "btn btn-primary" %>
              <% end %>
            </td>
            <td>
              <% if current_user.id == @group.owner_id %>
                <%= link_to "Edit", edit_group_path(@group), class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>