config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about", as: "about"

  resources :books, only: [:index, :show, :edit, :create, :update, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end

  get '/search', to: 'searchs#search'

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :liked_books, through: :favorites, source: :book
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :group_users
  has_many :groups, through: :group_users

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    # @books = @user.books
    @books = @user.books.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    @book = Book.new

    @today_books = @user.books.created_today
    @yesterday_books = @user.books.created_days_ago(1)
    @this_week_books = @user.books.created_this_week
    @last_week_books = @user.books.created_last_week
    # 前日比・前週比
    @the_day_before = ratio_post(@today_books, @yesterday_books)
    @compared_to_last_week = ratio_post(@this_week_books, @last_week_books)
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      @books = @user.books
      render "edit"
    end
  end

  def search
    @user = User.find(params[:user_id])
    # @books = @user.books.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      created_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{created_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ratio_post(books, prev_books)
    prev_books.count > 0 ? (books.count.to_f / prev_books.count.to_f) * 100 : " - "
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-success" %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
            <% end %>
          <% else %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<div class="col">
  <table class='table'>
    <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
    <tr>
  	  <th>name</th>
  	  <td><%= user.name %></td>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <td><%= user.introduction %></td>
    </tr>
    <tr>
  	  <th>follows</th>
  	  <td><%= link_to user.followings.count, user_followings_path(user.id) %></td>
    </tr>
    <tr>
  	  <th>followers</th>
  	  <td><%= link_to user.followers.count, user_followers_path(user.id) %></td>
    </tr>
  </table>
</div>
<div class="col">
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-success" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :POST, class: "btn btn-sm btn-success" %>
    <% end %>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> |
      <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'users/search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <div class='row'>
        <%= render 'info', user: @user %>

        <div class='col'>
          <% if current_user != @user %>
            <% if (current_user.following? @user) && (@user.following? current_user)  %>
              <%= link_to 'Begin Chat', chat_path(@user.id), class:"btn btn-sm btn-info" %>
            <% end %>
          <% end %>
        </div>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render 'books/index',books: @books %>

      <%= form_with url: user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at, class: "date_search" %>
        <%= f.submit '検索', class: 'btn btn-primary'  %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'users/search', search_book: @search_book %>
        <% end %>
      </div>


      <h2>投稿数の前日比・前週比</h2>
      <table class="table table-bordered">
        <thead>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </thead>
        <tbody>
          <td><%= @today_books.count %></td>
          <td><%= @yesterday_books.count %></td>
          <td><%= @the_day_before %> %</td>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <th>今週の投稿数</th>
          <th>前週の投稿数</th>
          <th>前週比</th>
        </thead>
        <tbody>
          <td><%= @this_week_books.count %></td>
          <td><%= @last_week_books.count %></td>
          <td><%= @compared_to_last_week %> %</td>
        </tbody>
      </table>
      <h2>7日分の投稿数</h2>
      <table class="table table-bordered">
        <thead>
          <th>6日前</th>
          <th>5日前</th>
          <th>4日前</th>
          <th>3日前</th>
          <th>2日前</th>
          <th>1日前</th>
          <th>今日</th>
        </thead>
        <tbody>
          <td><%= current_user.books.created_days_ago(6).count %></td>
          <td><%= current_user.books.created_days_ago(5).count %></td>
          <td><%= current_user.books.created_days_ago(4).count %></td>
          <td><%= current_user.books.created_days_ago(3).count %></td>
          <td><%= current_user.books.created_days_ago(2).count %></td>
          <td><%= @yesterday_books.count %></td>
          <td><%= @today_books.count %></td>
        </tbody>
      </table>
      <canvas id="myLineChart"></canvas>
      <script>
        const ctx = document.getElementById("myLineChart");
        const myChart = new Chart(ctx, {
          /* グラフの種類 (bar、line、rader、pie、doughnut、polarArea、bubble などがある) */
          type: "line",
          data: {
            /* 各項目のラベル(上から時計回り) */
            labels: [
              "6日前",
              "5日前",
              "4日前",
              "3日前",
              "2日前",
              "1日前",
              "今日",
            ],
            /* データの設定 */
            datasets: [
              {
                /* グラフ全体のラベル */
                label: "投稿した本の数",
                /* グラフのデータ(縦軸) */
                data: [
                  <%= current_user.books.created_days_ago(6).count %>,
                  <%= current_user.books.created_days_ago(5).count %>,
                  <%= current_user.books.created_days_ago(4).count %>,
                  <%= current_user.books.created_days_ago(3).count %>,
                  <%= current_user.books.created_days_ago(2).count %>,
                  <%= current_user.books.created_days_ago(1).count %>,
                  <%= current_user.books.created_days_ago(0).count %>
                ],
                /* データライン*/
                borderColor: '#00f',
                lineTension: 0.5,
                fill: false,
              }
            ],
          },
          options: {
            plugins: {
              // グラフタイトル
              title: {
                display: true,
                text: '7日間の投稿数の比較',
                color: 'black',
                padding: {top: 5, bottom: 5},
                font: {
                  family: '"Arial", "Times New Roman"',
                  size: 12,
                },
              },
              // 凡例
              legend: {
                position: 'top',
                align: 'center',
                // 凡例ラベル
                labels: {
                  boxWidth: 20,
                  boxHeight: 8,
                },
                // 凡例タイトル
                title: {
                  display: false,
                  text: 'Legend',
                  // padding: {top: 20},
                },
              },
              // ツールチップ
              tooltip: {
                backgroundColor: '#933',
              },
            },
            scales: {
              y: {
                // 最小値・最大値
                min: 0,
                max: 6,
                // 軸タイトル
                title: {
                  display: false,
                  text: 'Scale Title',
                  color: 'blue',
                },
                // 目盛ラベル
                ticks: {
                  color: 'blue',
                  stepSize: 1,
                  showLabelBackdrop: true,
                  backdropColor: '#fff',
                  backdropPadding: { x: 4, y: 2 },
                  major: {
                    enabled: false,
                  },
                  align: 'end',
                  crossAlign: 'center',
                  sampleSize: 4,
                },
                grid: {
                  // 軸線
                  borderColor: '#efefef',
                  borderWidth: 1,
                  drawBorder: true,
                  // 目盛線＆グリッド線
                  color: '#ccc',
                  display: true,
                  // グリッド線
                  // borderDash: [3, 3],
                  borderDashOffset: 0,
                  // 目盛線
                  drawTicks: false,
                  tickColor: 'blue',
                  tickLength: 10,
                  tickWidth: 2,
                  // tickBorderDash: [2, 2],
                  tickBorderDashOffset: 0,
                },
              },
              x: {
                grid: {
                  borderColor: '#ccc',
                  borderWidth: 2,
                },
              },
            },
          },
        });
      </script>
    </div>
  </div>
</div>